### ISSUE TITLE
Refusal To Connect

### ISSUE THREAD

**Issue by guardiandesigns** [alexcambose/x-frame-options#2]
Pinging back the following:

[root@secure ~]# npm run start

> x-frame-options-bypass@1.0.0 start /root
> node index.js

Listening on port 3000!
GET /?url=https://example.com/ 200 1291 - 119.475 ms
TypeError: URL is not a constructor
   at data.toString.replace (/root/index.js:40:43)
   at RegExp.[Symbol.replace] (native)
   at RegExp.[Symbol.replace] (native)
   at String.replace (native)
   at axios.get.then (/root/index.js:33:40)
   at process._tickCallback (internal/process/next_tick.js:109:7)

**Comment by alexcambose** [comment]
This is fixed.
